"""importing necessary modules"""
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
"""declarativ base State class
class definition of a State and an instance Base = declarative_base():

"""
Base = declarative_base()
"""State class:
columns:
  -id is the primary and autogenerated
   - name not null"""
class States(Base):
    __tablename__ = 'states'
    id = Column(Integer, primary_key=True, nullable=False)
    name =  Column(String(128), nullable=False)
    